from typing import Protocol
from domain.models import Conversation, User

class ConversationStore(Protocol):

    def get_by_user(self, user: User) -> Conversation | None: ...
    def save(self, conversation: Conversation) -> None: ...
    def delete_by_user(self, user: User) -> None: ...
